# Generated by Django 5.0.1 on 2024-01-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
